SKILL_ALIASES = {
    "react.js": "react",
    "reactjs": "react",
    "react js": "react",
    "node.js": "node",
    "nodejs": "node",
    "node js": "node",
    "express.js": "express",
    "expressjs": "express",
    "postgresql": "postgres",
    "postgres sql": "postgres",
    "mongodb database": "mongodb",
    "scikit-learn": "scikit learn",
    "sklearn": "scikit learn",
    "machine-learning": "machine learning",
    "deep-learning": "deep learning",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "amazon web services": "aws",
    "microsoft azure": "azure",
    "google cloud platform": "gcp",
    "k8s": "kubernetes",
}


SKILL_FAMILIES = {
    "frontend": {
        "react",
        "angular",
        "vue",
        "javascript",
        "typescript",
        "html",
        "css",
        "redux",
    },
    "backend": {
        "python",
        "java",
        "node",
        "express",
        "fastapi",
        "django",
        "flask",
        "spring",
        "c++",
        "c#",
    },
    "data": {
        "python",
        "pandas",
        "numpy",
        "spark",
        "hadoop",
        "hive",
        "mapreduce",
        "sql",
        "postgres",
        "mongodb",
    },
    "ml": {
        "machine learning",
        "deep learning",
        "tensorflow",
        "pytorch",
        "scikit learn",
        "keras",
        "nlp",
        "computer vision",
    },
    "cloud_devops": {
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "jenkins",
        "ci/cd",
    },
}


RELATED_SKILLS = {
    ("redux", "react"),
    ("react", "redux"),
    ("javascript", "react"),
    ("typescript", "react"),
    ("python", "machine learning"),
    ("machine learning", "python"),
    ("tensorflow", "pytorch"),
    ("pytorch", "tensorflow"),
    ("keras", "tensorflow"),
    ("tensorflow", "keras"),
    ("docker", "kubernetes"),
    ("kubernetes", "docker"),
    ("fastapi", "api development"),
    ("django", "web development"),
    ("flask", "web development"),
}


ADJACENT_SKILLS = {
    ("angular", "react"),
    ("react", "angular"),
    ("vue", "react"),
    ("react", "vue"),
    ("java", "python"),
    ("python", "java"),
    ("tensorflow", "pytorch"),
    ("pytorch", "tensorflow"),
    ("aws", "azure"),
    ("azure", "aws"),
    ("aws", "gcp"),
    ("gcp", "aws"),
    ("azure", "gcp"),
    ("gcp", "azure"),
}
